### ISSUE TITLE
Automatically check which ZairaChem descriptors are being used

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/olinda#9]
ZairaChem is built in such a way that if one descriptor is not calculated for any reason, the pipeline still proceeds. Yet, it seems that Olinda expects all the descriptors to be there, and if they are not, it crashes. See example below for a model with missing Mordred Descriptors:

```
Traceback (most recent call last):
  File "/home/gturon/github/olinda_test.py", line 3, in <module>
    student_model = distill("dili")
  File "/home/gturon/github/zaira-chem/src/olinda/src/olinda/distillation.py", line 83, in distill
    student_training_dm = gen_model_output(featurized_smiles_dm, model, working_dir, num_data, clean)
  File "/home/gturon/github/zaira-chem/src/olinda/src/olinda/distillation.py", line 332, in gen_model_output
    preds = model(smiles_input_path)
  File "/home/gturon/miniconda3/envs/zairachem/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gturon/github/zaira-chem/src/olinda/src/olinda/generic_model.py", line 70, in forward
    return self.nn(x)
  File "/home/gturon/github/zaira-chem/src/olinda/src/olinda/utils.py", line 72, in execute
    return zp.predict()
  File "/home/gturon/github/zaira-chem/src/olinda/src/olinda/models/zairachem.py", line 48, in predict
    self.run_descriptors(d)
  File "/home/gturon/github/zaira-chem/src/olinda/src/olinda/models/zairachem.py", line 86, in run_descriptors
    d._treated_descriptions()
  File "/home/gturon/github/zaira-chem/zairachem/descriptors/describe.py", line 39, in _treated_descriptions
    TreatedDescriptors().run()
  File "/home/gturon/github/zaira-chem/zairachem/descriptors/treated.py", line 268, in run
    algo = algo.load(os.path.join(trained_path, algo._name + ".joblib"))
  File "/home/gturon/github/zaira-chem/zairachem/descriptors/treated.py", line 49, in load
    return joblib.load(file_name)
  File "/home/gturon/miniconda3/envs/zairachem/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/gturon/github/dili/descriptors/mordred/nan_filter.joblib'
```

You can find the descriptors that were actually calculated in `model_folder/descriptors/done_eos.json`

**Comment by JHlozek** [comment]
This is implemented in line 100-105 of ```utils/zairachem/zairachem.py```.

Olinda checks the done_eos.json file for the descriptors used. If the descriptor is not one of the cached copies in the S3 bucket, then it runs the ErsiliaModel Python api to calculate the custom descriptor model.

**Comment by GemmaTuron** [comment]
Fantastic thanks @JHlozek
